### ISSUE TITLE
[Feat] TopBar, Header 구현

### ISSUE THREAD

**Issue by hj9118** [nodak-v2/Nodak-FE#22]
## 🤷‍♂️ 내용 요약

- [ ] TopBar (뒤로가기만 존재하는 헤더) 구현
- [ ] Header (타이틀, 알림, 검색 포함) 구현

## 📒 특이사항
피그마 구현사항을 토대로 진행합니다.

참고 이미지
- TopBar
![image](https://github.com/nodak-v2/Nodak-FE/assets/104545906/243cde40-08ea-4bad-8edf-88bb623f4389)

- Header 
![image](https://github.com/nodak-v2/Nodak-FE/assets/104545906/99bfeb2f-3c6b-41db-ba24-8daa5f1f2e3d)

**Comment by HoberMin** [comment]
지호님 혹시 구현하실 때 다른페이지에서도 활용할 수 있게 
compound pattern으로 구현해주실 수 있으신가요??

**Comment by HoberMin** [comment]
https://fe-developers.kakaoent.com/2022/220731-composition-component/

슥슥 봤는데 이글 참고해보면 좋겠네요

**Comment by HoberMin** [comment]
https://github.com/BoardSignal/Team-CivilWar-BoardSignal-FE/pull/26
